<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * adresseCabinetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class adresseCabinetRepository extends \Doctrine\ORM\EntityRepository
{
}
