<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * horaireTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class horaireTravailRepository extends \Doctrine\ORM\EntityRepository
{
}
