<?php

namespace Sante\SpecialisteBundle\Repository;

/**
 * specialisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class specialisteRepository extends \Doctrine\ORM\EntityRepository
{
}
